### PR TITLE
Fix: Ensure consistent IP capture across request methods

### PR DESCRIPTION
**Pull request by ivan-cavero**
**Hello there!**

I hope this message finds you well. I've been working on an issue we've encountered where the client's IP address wasn't consistently captured across different HTTP request methods in Elysia. After some investigation and trial, I've come up with a solution that seems to work well, at least from what I've been able to test so far. However, it certainly needs a thorough review and testing to ensure robustness.

Here's a summary of the changes I've made:

**Switch from derive to onRequest:** The use of derive was causing inconsistencies, particularly with GET requests where the IP was not always available. By moving the logic to the onRequest hook, we capture the IP at the earliest point in the request lifecycle.

**Store IP in the application state**: Instead of returning an object from derive, we're now storing the client's IP directly in Elysia's global state. This means that throughout the lifecycle of the request, we have a consistent and accessible place to get the client's IP.

**Breaking Change Warning**: It's important to note that this update changes the way developers will access the client's IP. Instead of destructuring the IP from the request, we will now access it through the store as store.ip. This will require updates to the existing code where the IP address is being used.

**Notes:**

I'd like to mention that this is my first contribution to this project, and I'm still on the learning curve with TypeScript. So, while I've done my best to ensure type correctness and adhere to the project's contribution, I'm very open to feedback. If there are any typing errors or best practices I might have overlooked, please do let me know. I'm eager to learn and improve.

Thank you for your understanding and patience. I appreciate the opportunity to contribute!

**Example:**
```
app.get(
    "/short-link/:shortUrl", ({ store, params: { shortUrl } }) => {
        rateLimiter(store.ip)
        return getShortLink(shortUrl)
    },
    {
        detail: {
            summary: "Get the number of short links",
            tags: ["short-links"]
        }
    }
)
app.post(
"/short-links", ({ store, body }) => {
          rateLimiter(store.ip)
          return createShortLink(body.url, body.shortUrl);
},
{
	body: t.Object(
		{
		  url: t.String(),
                  shortUrl: t.String()
		},
		{
			description: "Expected a url"
		}
	),
	detail: {
		summary: "Create a new short link",
		tags: ["short-links"]
	}
})
```

### CODE REVIEW

**Comment by gaurishhs** [comment]
Hello! First of all thank you so much for contributing. 

I have gone through all the changes and we cannot switch to `onRequest` because we can have typings only in derive and not in `onRequest`. 

I feel like storing every request ip to the global store would be inefficient in terms of memory and req/s. I would be really happy if you coud post some benchmarks comparing the revised version and current. 

Thanks

**Comment by ivan-cavero** [comment]
> Hello! First of all thank you so much for contributing.
> 
> I have gone through all the changes and we cannot switch to `onRequest` because we can have typings only in derive and not in `onRequest`.
> 
> I feel like storing every request ip to the global store would be inefficient in terms of memory and req/s. I would be really happy if you coud post some benchmarks comparing the revised version and current or i can benchmark next week i get to my machine.
> 
> Thanks


Hello!

Following your request for benchmarks comparing the original and revised versions, I've conducted some performance tests. This is my first attempt at such benchmarks, so I'd appreciate further review. Here's a summary of my findings, including the tools used:

**Testing Environment and Methodology**
- Benchmarking Tools: bombardier for req/s and latency tests, and Bun's built-in heapStats() for memory usage.
- Test Parameters: Simulated 125 concurrent connections for 30 seconds.
- Environment: Local development setup running on Windows 11.

| Metric                        | Original Version   | Modified Version  |
|-------------------------------|--------------------|-------------------|
| **Initial Heap Size**         | 3,864,542 bytes    | 3,860,543 bytes   |
| **Initial Heap Capacity**     | 6,407,134 bytes    | 6,405,247 bytes   |
| **Initial Extra Memory Size** | 1,434,590 bytes    | 1,432,703 bytes   |
| **Initial Object Count**      | 31,862 objects     | 31,845 objects    |
| **Reqs/sec**                  | 14,393.30          | 14,981.73         |
| **Avg Latency**               | 8.68ms             | 8.34ms            |
| **Throughput**                | 8.81MB/s           | 8.57MB/s          |
| **Final Heap Size**           | 48,658,527 bytes   | 59,945,545 bytes  |
| **Final Extra Memory Size**   | 45,203,247 bytes   | 56,174,649 bytes  |
| **Final Object Count**        | 109,279 objects    | 128,981 objects   |

**Comment by gaurishhs** [comment]
The memory difference tells a lot. It probably won't be suitable for high-scale usage handling thousands of req/s every day. 

I am confused about req/s though, will check myself once when i get back home

**Comment by gaurishhs** [comment]
Thanks for your efforts! But due to the memory usage and types issue i will not be merge this PR. 

Cheers

**Pull request closed without merging**
